
#ifndef OPENCL_WRAPPERS_OPENCL_HPP_
#define OPENCL_WRAPPERS_OPENCL_HPP_

// Declarations

#include "opencl/types.hpp"
#include "opencl/error.hpp"
#include "opencl/version.hpp"
#include "opencl/platform.hpp"
#include "opencl/device.hpp"
#include "opencl/context.hpp"
#include "opencl/queue.hpp"
#include "opencl/event.hpp"
#include "opencl/context_device.hpp"
#include "opencl/memory.hpp"
#include "opencl/kernel.hpp"
#include "opencl/program.hpp"
#include "opencl/program/source.hpp"
#include "opencl/program/compile.hpp"
#include "opencl/program/link.hpp"
#include "opencl/build_info.hpp"
#include "opencl/memory_object.hpp"
#include "opencl/buffer.hpp"
#include "opencl/pipe.hpp"
#include "opencl/identify.hpp"
#include "opencl/launch.hpp"
#include "opencl/sampler.hpp"
#include "opencl/image.hpp"
#include "opencl/options/compilation.hpp"
#include "opencl/options/link.hpp"
#include "opencl/builders/memory_object.hpp"
#include "opencl/builders/launch_config.hpp"
#include "opencl/builders/buffer.hpp"
#include "opencl/builders/image.hpp"

// Implementations

#include "opencl/impl/info.hpp"
#include "opencl/impl/miscellany.hpp"
#include "opencl/impl/version.hpp"
#include "opencl/impl/platform.hpp"
#include "opencl/impl/device.hpp"
#include "opencl/impl/memory.hpp"
#include "opencl/impl/queue.hpp"
#include "opencl/impl/device_capabilities.hpp"
#include "opencl/impl/error.hpp"
#include "opencl/impl/identify.hpp"
#include "opencl/impl/context.hpp"
#include "opencl/impl/context_device.hpp"
#include "opencl/impl/memory_object.hpp"
#include "opencl/impl/buffer.hpp"
#include "opencl/impl/kernel.hpp"
#include "opencl/impl/launch_config.hpp"
#include "opencl/impl/build_info.hpp"
#include "opencl/impl/device.hpp"
#include "opencl/impl/event.hpp"
#include "opencl/impl/pipe.hpp"
#include "opencl/impl/launch.hpp"
#include "opencl/impl/program.hpp"
#include "opencl/impl/program/source.hpp"
#include "opencl/impl/program/compile.hpp"
#include "opencl/impl/program/link.hpp"
#include "opencl/impl/sampler.hpp"
#include "opencl/impl/image.hpp"
#include "opencl/impl/builders/memory_object.hpp"
#include "opencl/impl/builders/buffer.hpp"
#include "opencl/impl/builders/image.hpp"

#endif // OPENCL_WRAPPERS_OPENCL_HPP_
